# render.yaml
services:
  - type: web
    name: realtime-predictor-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TZ
        value: Africa/Nairobi

  - type: web
    name: realtime-predictor-frontend
    env: python
    plan: free
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        fromService:
          name: realtime-predictor-backend
          type: web
      - key: TZ
        value: Africa/Nairobi
